### ISSUE TITLE
Bitfinex Margin trading !

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#101]
Hello again,

Maybe can be interesting to enable margin trading on bitfinex.

The only difference is:

"Trading pairs symbols are formed prepending a "t" before the pair (i.e tBTCUSD, tETHUSD).
Margin currencies symbols are formed prepending a "f" before the currency (i.e fUSD, fBTC, ...)".

Then we would chose in "exchange name" in the conf file either "Bitfinex" or "Bitfinex_margin".

**Comment by ctubio** [comment]
awesome'¡ will look at it  soOn''

**Comment by ctubio** [comment]
mm.. seems it have more differences, for example the new symbol is fUSD, and previously we had tBTCUSD, i mean there is only 1 currency not 2 xD

soo.. in the configs, instead of :
    "TradedPair": "BTC/USD",
we should have:
    "TradedPair": "USD",
?

if so, we can maybe keep the same exchange name, and detect if is margin trading if there is no / symbol in the tradepair value
