### ISSUE TITLE
BUG: APR

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#11]
Hello Carles,

Sorry for flooding you with issues but I've just discovered this one.

APR is a useful feature that get activated only when your holdings are outside of the fixed pDiv range of tbp. In that situation it will change the size of your order (to a maximum of 3x set order Sz) so that the next trade will bring your holdings exactly back on tbp.

The problem is that tribeca needs to hold 2x one order size to correctly send the to the market but APR ignores that.

So when APR is on and:
Diff. between your holding and tpb (Or 3x set order Sz) > 2x your holdings = Tribeca stops quoting.

Proposed fix:
Fixing a limit for apr orders = 1/2 holding.

One example to make myself clear:

I have 2btc in my account, one in BTC and one in Fiat and I'm using APR, ApMode Ewma Basic  and a 0.25btc pdiv and 0.25 bdSiz

Suddenly the market goes up and tpb reaches 1.7, APR gets activated and my bot will try to make a buy order of 0.7 to reach tbp.

However as I only have 1btc worth of euro in my account, tribeca gets blocked and no persistent trade is sent to the market.

I believe it is only one thing to change here:

https://github.com/ctubio/tribeca/blob/master/src/service/quoting-engine.ts#L103 L103 and L110.
```
  if (params.aggressivePositionRebalancing)
                unrounded.bidSz = Math.min(params.aprMultiplier*params.buySize, targetBasePosition - totalBasePosition);
 if (params.aggressivePositionRebalancing)
                unrounded.askSz = Math.min(params.aprMultiplier*params.sellSize, totalBasePosition - targetBasePosition);`
```
I'm not a coder but if I had to guess it would be:
unrounded.bidSz = Math.min(params.aprMultiplier*params.buySize, targetBasePosition - totalBasePosition, **totalBasePostion / 2**);`

And same for askSz with the variable for the fiat variable.

I hope I'm right so this bug can be easily fixed!

(PS: I'm trying it (only for bidSz) i'll let you know if it works!
Update: Well it doesn't work...)

**Comment by ctubio** [comment]
morning Camille'¡
thanks for the report, i noticed it too since forever so we will need to get hands dirty sOOn.

in my roadmap ewma and apr are still pending to be learned :sob:, i understand from the user point of view what is the functional expectation, but didnt dig yet into the codes. To fully control them i want to display in the ui no only the internal ewma values but also all internal (and relevant for the user) states of the app simplified as semaphores or colorful flags somewhere. Once the information is completely under control of the user (and me), my plan is to start with the maths behind.

before add new ui elements, i really want to fix the current ones, because currently there is already a super massive waste of server bandwidth and client bandwidth/cpu/memory.

so let me go step by step :P sorry for the waiting time meanwhile'¡!

#flooding_for_a_better_world

**Comment by Camille92** [comment]
Ahah understood.

Yes the new grid can be a bit heavy for my browser.
Good luck with the web UI!

No rush, and thank you for putting that much efforts into tribeca recently :)

**Comment by ctubio** [comment]
I added another minimum, as half of the amount free for trade on each side.

now it will use as a bid/ask size the smaller of (if apr is on):
- tbp - (amount free + amount held)
- size * aprMultiplier (defined as 3 in [main.ts](https://github.com/ctubio/tribeca/blob/master/src/service/main.ts#L119) [no ui config])
- amount free / 2

Usually the smaller is always `size * aprMultiplier` (because the side with funds enough to trade when apr is on is always the side with more funds, so as long as you dont set 100% of your funds in the size of each trade, is supposed that 3 sizes is a small value compared to all sizes that happened until apr was finally enabled).
