### ISSUE TITLE
Ping or Pong on open orders

### ISSUE THREAD

**Issue by zachaller** [ctubio/tribeca#124]
Not sure if this is something anybody would want but I think it would be nice to have a column on the open orders that say weather it is a Ping or a Pong if that is possible I do not know if it is tribeca knows before it places an order if it is a Ping or a Pong

**Comment by ctubio** [comment]
morning'¡
a sell order is always a pong when buyPing is non-zero, and also a buy order is always a pong when sellPing is non-zero. otherwise if buyPing is zero then sell orders are pings, and if sellPing is zero buy orders are pings.

hope having this info avoids the need of a column in the orders grid.

**Comment by ctubio** [comment]
anyway ima try to add this info to `side` column someday somehow, thanks for the idea'¡

(:bulb: would be nice to attach the related trade id of the ping into the pong quote, so no need to recalculated the matching ping after complete pong orders)
