### ISSUE TITLE
Docker failed to build

### ISSUE THREAD

**Issue by zbanga** [ctubio/tribeca#127]
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"node_modules/.bin/forever\": stat node_modules/.bin/forever: no such file or directory".

**Comment by ctubio** [comment]
forever is included at https://github.com/ctubio/tribeca/blob/master/package.json#L49, so i believe the installation didnt finnished for whatever reason (only Docker knows), i suggest to not use Docker (alternatively retry Docker installation but makig sure Docker have everything it needs [try to clean old unused images/containers if any that may be eating space])

but may be another problem before this, because this is at the very end when forever tries to be executed. i think must be another error message at the installation time (the very first log of the very first run of the image, because next logs may not show installation steps [the real interesting log] but app execution [the log you pasted])
