### ISSUE TITLE
How to run multiple tribeca on one computer ?

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#40]
Just a technical question,

I run all my tribecas each on small ec2 instances. I think it can be good to have them on the same one but I don't know how to manage that with mongo and the ports that need to be opened.

**Comment by ctubio** [comment]
Hello Camille¡'

to run the app concurrently multiple times in the same computer:
* git clone to differente folders, doesnt matter the dirnames and `npm install`
* edit `etc/tribeca.json` files of each and set a different `MongoDbUrl`,** you can only modify the last word of the url, that is the database name to be created; one different for each app, you could have: `mongodb://localhost:27017/tribeca` and for another `mongodb://localhost:27017/whatevername` and `mongodb://localhost:27017/tribeca69` for another app
* also set different `WebClientListenPort` numbers for each app so they dont collide and are all accessible.

hope it helps'¡

**Comment by Camille92** [comment]
Thanks!

**Comment by Camille92** [comment]
I tried to do it using docker, but so far I can't get it running.

In the second dockerfile I just need to change a bit the last world of MongoDbUrl and the web client port.
But do I need to run a new Mongo service or use 1 mongo for 2 tribeca ?
But then I need to change that right ?
'''
docker run -p 3000:3000 --link tribeca-mongo:mongo --name tribeca -d tribeca
'''

**Comment by ctubio** [comment]
Hello Camille,
only 1 mongodb server in localhost can store multiple tribeca databases by giving to the databases diferent names.

The database name is defined as the last word of the `MongoDbUrl` value.

The docker run line, is not setting up any database name, it is setting up docker containers linked together, and the containers happens to have the name "tribeca" and "tribeca-mongo"; do not confuse these container names in docker run line with the `MongoDbUrl` database name.

So, having multiple tribecas with different MongoDbUrl values, if these are containers, you need also to give to these containers different names, lets say an example could be:

App¡ 1:
* have MongoDbUrl as mongodb://localhost:27017/tribeca
* have docker container name as tribeca
* have docker container name as tribeca-mongo

App¡ 2:
* have MongoDbUrl as mongodb://localhost:27017/whatevername
* have docker container name as something
* have docker container name as somethingdatabase

Or you can make App 2 also like:
* have MongoDbUrl as mongodb://localhost:27017/whatever
* have docker container name as something
* have docker container name as  tribeca-mongo

that is, for reuse the mongo server/container and just create separated database for each app (recommeneded instead of multiple redundant mongo servers/containers)

If you have the apps in containers, all them can have the same WebClientListenPort.

Hope this helps'¡

**Comment by ctubio** [comment]
new simplified how to at https://github.com/ctubio/tribeca#multiple-instances-party-time
