### ISSUE TITLE
How to determine profitable configs

### ISSUE THREAD

**Issue by holoiii** [ctubio/tribeca#51]
How is everyone determining which configs to use for their strategy? Are the defaults any good, for example for AK47?

For example, for BTC/USD right now on GDAX, the price is $1313.95 at the moment.

I'm using Ak-47 with:
1. 2 bullets
2. 0.25 range
3. pingAt both sides
4. pongAt shortpingpair
5. pingwidth 0.1
6. pongwidth 0.1
7. bidsize 0.02
8. asksize 0.01
9. fv bbo

I've been running this for several days and have seen pretty good results.

**Comment by ctubio** [comment]
Default values are usualy minimum acceptable values not optimized for nobody but for the general; feel free to experiment/calculate to find your best optimized values based in your total funds and the market conditions.

I usualy run multiple tribecas and adjust them every 12h to whatever configs are running best at the moment.

**Comment by Camille92** [comment]
> I usualy run multiple tribecas and adjust them every 12h to whatever configs are running best at the moument.

That's a lot of work!

But yes you need to do your own work. I use excel and compare the results with different settings over days to determine the most profitable.

But in the future configuration will be easier when tribeca will calculate volatility for determining the width. -> https://github.com/ctubio/tribeca/issues/46

**Comment by Camille92** [comment]
Given my 'experience' using tribeca, I would recommend you to put wider settings for your width.
Look at the BTC/USD chart of gdax either on the website or in tradinview and look how much price moves in 1mn in general. This gives you a pretty good idea of what can be your width settings.

**Comment by kristafari** [comment]
holoiii, the past few days have been a good uptrend.  the question is: are your results better than a buy & hold for the duration of the same time period?

**Comment by Camille92** [comment]
@kristafari Tribeca is by no mean a "magical" bot.
So no if bitcoin is up by 5% it will most likely not beat b&h.

However there are a few stats I can share with you according to my pasts results (I keep a record of all the daily results with tribeca compared to btc since last summer).

So Tribeca will most likely beat b&h it bitcoin rises by less than 1.5% in a day.
Tribeca will probably make a (small) profit if bitcoin goes down by 0.5% or less in a day.

Outside of this range, tribeca will get around 80% of a rise and take only 20% of a drop.
Ie : btc takes 10% -> I get 8%
Btc loses 10% -> I lost 2%

In the long run it's a big win over b&h.

Of course this is in general and depends on your settings / funds you have the market / markets you trade in.

Cheers and happy trading!

**Comment by ctubio** [comment]
a dummy (cos im no expert) solution is to have a high `tbp` value, instead of the tipical 50%, having for example 90% may help to avoid this loses while market goes up.

what takes us to the next question: while `apMode` is `off` and `%` is enabled, should we make `tbp` also optionally configurable by percentage like `pDiv` and  `bid/askSize`?

**Comment by Camille92** [comment]
@ctubio Yes why not!

**Comment by ctubio** [comment]
closing because no more technical work to do'¡ :( xD but thanks for the discussion'¡! (and the little new feature!) :)
