### ISSUE TITLE
Multiple licenses

### ISSUE THREAD

**Issue by caseyWebb** [ctubio/tribeca#57]
It doesn't really matter because they're equal for all intents and purposes, but there are both `COPYING` and `LICENSE` files, and they're different.

**Comment by ctubio** [comment]
yep, `LICENSE` file is from [michaelgrosner/tribeca](https://github.com/michaelgrosner/tribeca), since i do not care about licenses (nor liabilities), i have my own `COPYING` file, but mainly to make sure that i clearly state the copyable status of my projects; since both are compatible i keep them both, but i will like to delete `LICENSE` xD because i miss some verbs (that i love) in the content: use, copy, modify, merge, publish.

**Comment by ctubio** [comment]
:sunflower: btw, is yarn nicer than npm?

**Comment by caseyWebb** [comment]
yarn is awesome; I switched a while ago and never looked back. NPM installs feel like they take ages now.

**Comment by ctubio** [comment]
great news! ty'¡ lets consume cached packages then'¡ :D
