### ISSUE TITLE
IMPROVEMENT: Better performance for Boomerang and AK47

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#6]
Dear Carles,

A few months back I have noticed something that greatly undermine the performance of Boomerang (and now AK47).
I think everyone would make much more profit if it is fixed.

The problem happens when the market width is smaller than the fixed width.
When tribeca makes a bad trade, instead of going back to a "top" mode and respect the width for the next trade it will not respect the width and only try to close a previous old ping (that might be very old and not relevant).

Doing so can lead to some losses and for sure reduces the profitability of the bot.
I myself switched from Boomerang to PP  mid November because of that issue. (I can send you the data if you're interested).

I don't know if it's very clear so I give you an example using boomerang.

Lets say the price has been moving during the past 2 days between €800 and 1000€ a bitcoin.
Now it is around €900 with a set width of 2 and a market width of 0,1.
During the past two days, tribeca made some good and some bad trades so numerous ping are not closed above and under today's market price.

Instead of respecting the settings, tribeca will try to close old pings and offer quotations on both side of the market with the offered width of 0.1, putting the trader at risk for a very small profit.

I would advocate that tribeca should always respect the set width in order to be ready for future good trades, even though it reached a goal of an old ping.

I like how Pingpong does it by setting itself in "top" mode when it can't properly close a trade and I think this should be as well in AK47 and Boomerang.

Tell me what you think about it,

Camille

Example of this morning with settings of width set at 2
![capture d ecran 2017-01-09 a 11 23 20](https://cloud.githubusercontent.com/assets/6861590/21763423/21e0c110-d65e-11e6-8ff7-26bed3aba89b.png)

**Comment by ctubio** [comment]
moltes moltes gracies Camille!
i will read/investigate/reply next weekend.

**Comment by ctubio** [comment]
understood, i also believe tribeca must respect always the configs.

this is slightly related to [computeQtyLimit](https://github.com/ctubio/tribeca/blob/master/src/service/safety.ts#L83) method in SafetyCalculator class (it sets values of references) and ~~totaly~~ related to [computeQuote](https://github.com/ctubio/tribeca/blob/master/src/service/quoting-engine.ts#L71) method in QuotingEngine class (it sets what references are begin used).

Thank you alot for pointing out the issue! will try to fix asap ~~but may take long because of the tests~~.

Literal fix: unrounded.bidPx and unrounded.askPx must be reset only if is not already set with a higher value (to avoid placing lower quotes than GenerateQuote and ewmaProtection suggestions) at computeQuote method in QuotingEngine class.
Oops, this is already [done](https://github.com/ctubio/tribeca/blob/master/src/service/quoting-engine.ts#L120), the problem then is sure the crazy divisions i was testing back in the first days... im so sorry about it! (i mean the params.width / 8.0 of [ping-pong.ts](https://github.com/ctubio/tribeca/blob/master/src/service/quoting-styles/ping-pong.ts) should be all by 2.0 (same as Top).

**Comment by ctubio** [comment]
I think i will add an option (checkbox) to enable this aggressive quotes, but ***only for pongs***. As you said, pings must respect always the configs, but maybe is a good idea to ***optionally*** allow to make aggressive pongs?
thanks for your time Camille!

**Comment by Camille92** [comment]
It is never a bad idea to add new option!

But I I'm not sure to see how that would change from this issue (especially if you have ping at both side enable).

If I understand you correctly in practice it would be that whatever you ping you would pong it on top of the at whatever is the fixed width ?

If it is like that I think it's very risky as it would make the width irrelevant while it is responsible now for the degrees of "risk-profit-opportunity" you're willing to take.

**Comment by ctubio** [comment]
i think that's it, it will make the width irrelevant in the pong side always that there is a matching ping reference in the opposite side.

the discussion of the consequences of this option (maybe named HighRiskPongs! xD) could take us many pages :P maybe will be better to simply add the option to the app and ship it. xD (because im not sure, but i maaaaybe disagree with the adjective "irrelevant" as long as the width is respected [but respected based on the ping, not in the fair value])

many thanks again for your invaluable bug reporting and clever suggestions!

**Comment by ctubio** [comment]
this also closes michaelgrosner/tribeca/issues/83 :gift:
