### ISSUE TITLE
Improvement/ Bug fixe Cancel all open orders

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#64]
Hello Carles and everyone,

Given #59 #60 (I think) and the numerous "ghost orders issues" we had in the past.

And given that Tribeca has a built-in cancel all open orders on boot function.

Why not proposing as an option to cancel all orders every 5 minutes all the time.
I was thinking about the pros and cons of it and I came to this conclusion:

Cons:
_You might miss a trade during the milliseconds orders are canceled.
_ Harder to see bugs if they happen

Pros:
_ It's a durable and radical solution. It seems inevitable to have small issues with orders from time to time. Given that one tribeca can send up to 2000 orders a minute, it is logical that at some point some are not handled correclty (can be tribeca's or server's fault).
_ It solves the past, present, and future issues before they can have a negative impact on trading.

Well anyway I think it's a useful small feature that can really help and should not be hard to do as everything is already in tribeca :)

**Comment by ctubio** [comment]
morning Camille'¡ another little consequence of this is that then you can't have orders manually created in the exchange using the exchange website, because all they will be canceled every 5 min.

So maybe we can add a small checkbox? so ppl can choose to disable it in case they need to place manualy orders in the exchange too? ima go for that solution with the en/disable checkbox unless you disagree :P

**Comment by Camille92** [comment]
It's perfect! Thank you for that :)

**Comment by Camille92** [comment]
Hello and good morning,

After letting this version running for the night, the cancel orders has been working perfectly on all market but ETH/BTC where one order stayed for over 5h.

Any idea what can cause that issue ?

Cheers!

**Comment by ctubio** [comment]
donno, didnt experienced it; for me the 5min timeout always worked as far as i saw

it was open in tribeca and in the exchange? or only in one platform?

thanks'¡

**Comment by Camille92** [comment]
Yes exactly.

I updated the Tribeca yesterday night and set them up with the 5mn timeout. Then in the morning, I came to check on the exchanges if there are not "weird" orders.
And I found a 5h old order on ETH/BTC on Coinbase. A part from that everything seemed to get canceled properly :)

**Comment by ctubio** [comment]
i will carefully look for this, but let me keep the issue closed since seems working aaaaalmost always (always if you ask to me)
ty'¡

**Comment by Camille92** [comment]
For sure!

Maybe I'm doing something wrong from my side !

**Comment by ctubio** [comment]
nah, what it does in all gateways is to connect to the exchange to get a list of current open orders and later cancel them all one by one using http calls, in case there are more than 20 orders, maybe only the first 20 open orders found are only closed, but the rest if any should be closed in the next 5min timeout

i belive we cannot do it better xD (the 20 limit is because calls/seconds limit in the http APIs)
