### ISSUE TITLE
BUG using Bitcoin denominated market after https://github.com/ctubio/tribeca/commit/bb82451888990b3ddc4ab4b3355bb4e9a7e57f76

### ISSUE THREAD

**Issue by Camille92** [ctubio/tribeca#72]
Hello,

After the last update I'm a bit confused because trading with Alts doesn't seems to work well.

I don't know exactly what is doing that yet.

**Comment by Camille92** [comment]
I got paranoid. 
False alert sorry!

The problem was that no enough btc was left to execute apr orders.

**Comment by Camille92** [comment]
Turns out I wasn't too paranoid.

What's happening is that the new feature "has enough position" doesn't go well with alt when using %.

I just suppressed it and it works well again!

https://github.com/ctubio/tribeca/commit/bb82451888990b3ddc4ab4b3355bb4e9a7e57f76

**Comment by Camille92** [comment]
I think that we don't need this feature as:
_ I doesn't go well with percentage: The percentage of something is always something so Tribeca should always be able to trade.
_ Apr already has something to send order depending on what's left (previous update i don't remember which one)
_ If after all, we don't have enough fund -> no order is sent -> no problem

**Comment by ctubio** [comment]
yep i think the very same xD thats why i removed it in first place; but later i got brain f*ck and added it back again because some mod in upstream confused me as if it was needed (related to avoid sending order to the exchange when not enough funds); but i agree that this is the very last and worst moment where this can be checked, should be (and is already) done at a sooner step

ty for confirm the brain damage'¡ will fix soOn

**Comment by ctubio** [comment]
TODO: get rid of hasEnoughPosition method in quote-sender (and of positionBroker property)

**Comment by Camille92** [comment]
Thanks it reassures me as well that I was not crazy yesterday.

Can you please tell me what https://github.com/ctubio/tribeca/commit/4505416bfc2b3ddc5f26f7b597837b99ea100b10 is doing I'm very not sure haha

**Comment by ctubio** [comment]
lol, there was a time while i was not knowing how the gateways works, and i noticed too much useless traffic of order statuses (new orders begin new 2 times, reported to be worked maaany times, and canceled 3 or more times, and after begin canceled 3 times i is even continued to be reported as open a few more times; this happened for each single order, and i believe it still happens in upstream), i was gettingt really crazy, so added the `done` property, that deletes the order from memory as soon as done=true, so no more redundant status updates; but since little days ago i fully understood the gateways, fixed the workflow, and get rid of `done`property while removing orders from memory based only if status=Canceled/Rejected/Complete (cos now status value is unique and trustable).
